config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'homes#top'
  get 'introduction', to: 'homes#introduction'
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'search_diaries/suggestions', to: 'search_diaries#suggestions', as: 'search_diaries_suggestions'
  post 'search_means/suggestions', to: 'search_means#suggestions', as: 'search_means_suggestions'
  post '/callback', to: 'line_bot#callback'
  mount Sidekiq::Web => "/sidekiq"

  resources :reports, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :means do
    resources :mean_comments, only: [:create, :update, :destroy], module: :means
    resource :bookmark, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :diaries, only: [:index, :new, :create, :show, :destroy] do
    resource :stress_diagnosis, only: [:new, :create]
    resource :happy_diagnosis, only: [:new, :create]
    resources :diary_comments, only: [:create, :update, :destroy], module: :diaries
    resource :favorite, only: [:create, :destroy]
    resource :sympathy, only: [:create, :destroy]
  end

  namespace :mypage do
    get 'profiles/:id', to: 'profiles#view_users'
    resource :profile, only: [:show, :update] do
      resource :avatar, only: [:destroy], module: :profiles
      get 'recommended', to: 'profiles#show_recommended_means'
      resource :mynote, controller: 'profiles', only: [] do
        get :mymean
        get :bookmarks
        get :mydiary
        get :favorites
      end
      resource :chart, controller: 'profiles', only: [] do
        get :stress_chart
        get :happy_chart
      end
      resource :ranking, controller: 'profiles', only: [] do
        get :like_ranking
        get :like_ranking_in_past_month
        get :like_ranking_in_past_week
        get :sympathy_ranking
        get :sympathy_ranking_in_past_month
        get :sympathy_ranking_in_past_week
      end
    end
  end

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: [:index, :show, :destroy]
    resources :means, only: [:index, :show, :destroy]
    resources :diaries, only: [:index, :show, :destroy]
    resources :reports, only: [:index, :show, :update]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer id='footer' class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <div class="copyright">
          <p>Copyright © 2023. MARUI</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Stress Diary</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0 ms-auto">
          <li class="nav-item">
            <%= link_to '日記投稿一覧', diaries_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ストレス解消法一覧', means_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'TOPページ', root_path, class: 'nav-link' %>
          </li>
        <% if current_user.present? %>
          <li class="nav-item">
            <%= link_to '日記投稿作成', new_diary_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ストレス解消法作成', new_mean_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'マイページ', mypage_profile_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ログアウト', logout_path, class: 'nav-link', data: { turbo_method: :delete, turbo_confirm: 'ログアウトします' } %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>