config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'homes#top'
  get 'introduction', to: 'homes#introduction'
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'search_diaries/suggestions', to: 'search_diaries#suggestions', as: 'search_diaries_suggestions'
  post 'search_means/suggestions', to: 'search_means#suggestions', as: 'search_means_suggestions'
  post '/callback', to: 'line_bot#callback'
  mount Sidekiq::Web => "/sidekiq"

  resources :reports, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :means do
    resources :mean_comments, only: [:create, :update, :destroy], module: :means
    resource :bookmark, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :diaries, only: [:index, :new, :create, :show, :destroy] do
    resource :stress_diagnosis, only: [:new, :create]
    resource :happy_diagnosis, only: [:new, :create]
    resources :diary_comments, only: [:create, :update, :destroy], module: :diaries
    resource :favorite, only: [:create, :destroy]
    resource :sympathy, only: [:create, :destroy]
  end

  namespace :mypage do
    get 'profiles/:id', to: 'profiles#view_users'
    resource :profile, only: [:show, :update] do
      resource :avatar, only: [:destroy], module: :profiles
      get 'recommended', to: 'profiles#show_recommended_means'
      resource :mynote, controller: 'profiles', only: [] do
        get :mymean
        get :bookmarks
        get :mydiary
        get :favorites
      end
      resource :chart, controller: 'profiles', only: [] do
        get :stress_chart
        get :happy_chart
      end
      resource :ranking, controller: 'profiles', only: [] do
        get :like_ranking
        get :like_ranking_in_past_month
        get :like_ranking_in_past_week
        get :sympathy_ranking
        get :sympathy_ranking_in_past_month
        get :sympathy_ranking_in_past_week
      end
    end
  end

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: [:index, :show, :destroy]
    resources :means, only: [:index, :show, :destroy]
    resources :diaries, only: [:index, :show, :destroy]
    resources :reports, only: [:index, :show, :update]
  end
end

app/controllers/search_diaries_controller.rb
class SearchDiariesController < ApplicationController
  def suggestions
    @diaries = suggestions_for_diaries
  
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream:
            turbo_stream.update('suggestions',
                                partial: 'search_diaries/suggestions',
                                locals: { diaries: @diaries })
      end
    end
  end
  
  private
  
  def suggestions_for_diaries
    if params[:query].blank?
      Diary.all.order(created_at: :desc).page(params[:page]).per(5)
    else
      Diary.search(params[:query], fields: [:title], operator: 'or', match: :text_middle)
    end
  end
end

app/helpers/search_diaries_helper.rb
module SearchDiariesHelper
end

app/views/search_diaries/_form.html.erb
<%= form_with(url: diaries_path, method: :get, class: "w-60", data: {
    controller: "search",
    action: "keyup->search#suggestions",
    suggestions_url: search_diaries_suggestions_path,
}) do |form| %>
  <div>
    <div class="form-inline align-items-center mx-auto">
      <div class="col-auto"> 
        <%= form.text_field :query, data: {
                search_target: "input",
                action: "blur->search#hideSuggestions",
            },
            class: "w-full p-2 border border-gray-300 rounded-lg focus:outline-none focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200",
            placeholder: "Search...", autocomplete: "off" %>
      </div>
      <div class="col-auto">
        <%= form.submit "Search", class: "btn btn-outline-success" %>
      </div>
    </div>
    <div id="suggestions" class="absolute w-full mt-2 bg-white rounded-lg shadow-lg"
        data-search-target="suggestions" data-action="mousedown->search#childClicked">
      <%= render partial: "search_diaries/suggestions", locals: { diaries: @diaries } %>
    </div>
  </div>
<% end %>

app/views/search_diaries/_suggestions.html.erb
<% if @diaries.any? %>
  <div class="absolute w-full overflow-y-auto max-h-60 bg-white rounded-lg shadow-lg">
    <% @diaries.limit(5).each do |diary| %>
      <div class="p-2 border-b border-gray-300 hover:bg-gray-100">
        タイトル名：<%= link_to diary.title, diary_path(diary), class: "text-blue-500" %> /
        ユーザー名：<%= link_to diary.user.name, diary_path(diary), class: "text-blue-500" %>
      </div>
    <% end %>
  </div>
<% end %>