config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  root 'homes#top'
  get 'introduction', to: 'homes#introduction'
  get :sign_up, to: 'users#new'
  post :sign_up, to: 'users#create'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  post 'search_diaries/suggestions', to: 'search_diaries#suggestions', as: 'search_diaries_suggestions'
  post 'search_means/suggestions', to: 'search_means#suggestions', as: 'search_means_suggestions'
  post '/callback', to: 'line_bot#callback'
  mount Sidekiq::Web => "/sidekiq"

  resources :reports, only: [:new, :create]
  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :means do
    resources :mean_comments, only: [:create, :update, :destroy], module: :means
    resource :bookmark, only: [:create, :destroy]
    resource :like, only: [:create, :destroy]
  end

  resources :diaries, only: [:index, :new, :create, :show, :destroy] do
    resource :stress_diagnosis, only: [:new, :create]
    resource :happy_diagnosis, only: [:new, :create]
    resources :diary_comments, only: [:create, :update, :destroy], module: :diaries
    resource :favorite, only: [:create, :destroy]
    resource :sympathy, only: [:create, :destroy]
  end

  namespace :mypage do
    get 'profiles/:id', to: 'profiles#view_users'
    resource :profile, only: [:show, :update] do
      resource :avatar, only: [:destroy], module: :profiles
      get 'recommended', to: 'profiles#show_recommended_means'
      resource :mynote, controller: 'profiles', only: [] do
        get :mymean
        get :bookmarks
        get :mydiary
        get :favorites
      end
      resource :chart, controller: 'profiles', only: [] do
        get :stress_chart
        get :happy_chart
      end
      resource :ranking, controller: 'profiles', only: [] do
        get :like_ranking
        get :like_ranking_in_past_month
        get :like_ranking_in_past_week
        get :sympathy_ranking
        get :sympathy_ranking_in_past_month
        get :sympathy_ranking_in_past_week
      end
    end
  end

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: [:index, :show, :destroy]
    resources :means, only: [:index, :show, :destroy]
    resources :diaries, only: [:index, :show, :destroy]
    resources :reports, only: [:index, :show, :update]
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reporter, class_name: "User"
  belongs_to :reported, class_name: "User"

  def self.reported_count(user_id)
    where(reported_id: user_id).count
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::BaseController
  def index
    @reports = Report.all
  end

  def show
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    if @report.update(report_params)
      redirect_to admin_reports_path
    end
  end

  private

  def report_params
    params.require(:report).permit(:reason)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  #before_action :set_reported, only: %i[new create]

  def new
    @report = Report.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @report = Report.new(report_params)
    @report.reporter_id = current_user.id
    @report.reported_id = @user.id
    if @report.save
      redirect_to mypage_path(@user), success: 'ユーザーを通報しました'
    else
      render :new
    end
  end

  private

  #def set_reported
  #  @user = User.find(params[:user_id])
  #end

  def report_params
    params.require(:report).permit(:reason)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/admin/reports/index.html.erb
<div class="card">
  <div class="card-body">
    <h3 class="card-title">通報一覧</h3>
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>通報日</th>
            <th>被通報者名</th>
            <th>通報された回数</th>
          </tr>
        </thead>
        <tbody>
          <% @reports.each do |report| %>
            <tr>
              <td><%= report.created_at %></td>
              <td><%= link_to report.reported.name, admin_report_path(report) %></td>
              <td><%= Report.where(reported_id: report.reported_id).count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/reports/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h2>被通報者詳細</h2>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row">被通報者ID</th>
          <td><%= @report.reported_id %></td>
        </tr>
        <tr>
          <th scope="row">被通報者名</th>
          <td><%= @report.reported.name %></td>
        </tr>
        <tr>
          <th scope="row">通報された回数</th>
          <td><%= Report.where(reported_id: @report.reported_id).count %></td>
        </tr>
        <tr>
          <th scope="row">通報者ID</th>
          <td><%= @report.reporter_id %></td>
        </tr>
        <tr>
          <th scope="row">通報者名</th>
          <td><%= @report.reporter.name %></td>
        </tr>
        <tr>
          <th scope="row">通報理由</th>
          <td><%= @report.reason %></td>
        </tr>
      </table>
    </div>
  </div>
</div>